# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: patient_adapter_unary.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'patient_adapter_unary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bpatient_adapter_unary.proto\"\x17\n\tPatientID\x12\n\n\x02id\x18\x01 \x01(\t\"k\n\x0e\x41\x64\x61ptedPatient\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nbirth_date\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x1a\n\x12health_care_system\x18\x05 \x01(\t2E\n\x15PatientAdapterService\x12,\n\x0bget_patient\x12\n.PatientID\x1a\x0f.AdaptedPatient\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'patient_adapter_unary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PATIENTID']._serialized_start=31
  _globals['_PATIENTID']._serialized_end=54
  _globals['_ADAPTEDPATIENT']._serialized_start=56
  _globals['_ADAPTEDPATIENT']._serialized_end=163
  _globals['_PATIENTADAPTERSERVICE']._serialized_start=165
  _globals['_PATIENTADAPTERSERVICE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
